stages:
  - test
  - check
  - publish

tests:
  stage: test
  image: rust
  script:
    - cargo test

build:amd64:
  stage: check
  image: rust
  script:
    - cargo check
  artifacts:
    paths:
      - target/release/rust-gitlab-example

rustdoc:
  stage: check
  image: rust
  script:
    - cargo doc --no-deps --lib --release
  artifacts:
    paths:
      - target/doc
    
pages:
  stage: publish
  image: alpine
  dependencies:
    - build:amd64
    - rustdoc
  script:
    - mkdir -p public
    - mv target/doc/* public/
  artifacts:
    paths:
      - public
  only:
    - main